# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: |
        ng build --prod --base-href https://marc-apps.nl/
        cp /dist/index.html /dist/404.html
    - name: Config git
      run: |
        git config --global user.name "GitHub Actions Continuous Delivery service"
        git config --global user.email "16156117+Marc-JB@users.noreply.github.com"
    - name: Connect to git
      run: git clone https://Marc-JB:${{secrets.GIT_TOKEN}}@github.com/Marc-Apps/Marc-Apps.github.io.git /repo
    - name: Move .git directory
      run: |
        mkdir --mode=777 /dist/.git/
        cp -r /repo/.git/ /dist/.git/
    - name: Copy CNAME, README, LICENSE
      run: |
        [[ ! -f /repo/CNAME ]] || cp /repo/CNAME /dist/CNAME
        [[ ! -f /repo/README.md ]] || cp /repo/README.md /dist/README.md
        [[ ! -f /repo/LICENSE ]] || cp /repo/LICENSE /dist/LICENSE
    - name: Publish
      run: |
        cd /dist
        git add -A
        git commit -m "GitHub Actions Continuous Delivery release"
        git push origin master
