name: Angular PR validation

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: pr-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    uses: ./.github/workflows/analysis-job.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
