name: Angular Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: angular-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # Cache
      - name: Angular cache
        uses: actions/cache@v3
        with:
          path: ./.angular/cache
          key: ${{ runner.os }}-angular

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install -g @angular/cli
          npm ci

      # Build
      - name: Build project
        run: ng build --base-href https://marc-apps.nl/

      # Deploy to GitHub Pages
      - name: Copy README, CNAME, etc.
        run: |
          cp ./dist/browser/index.html ./dist/browser/404.html
          cp ./CNAME ./dist/browser/CNAME || echo "No CNAME"
          cp ./README.md ./dist/browser/README.md || echo "No README.md"
          cp ./LICENSE ./dist/browser/LICENSE || echo "No LICENSE"
          cp ./dist/3rdpartylicenses.txt ./dist/browser/3rdpartylicenses.txt || echo "No 3rdpartylicenses.txt"

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./dist/browser/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
